use serde::Deserialize;

use crate::error::ConfigError;

#[derive(Debug, Clone, Default, Deserialize)]
#[serde(default)]
pub struct Config {
    pub scheduling: SchedulingConfig,
    pub display: DisplayConfig,
    pub hooks: HooksConfig,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(default)]
pub struct SchedulingConfig {
    pub max_interval: u32,
    pub new_card_limit: u32,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(default)]
pub struct DisplayConfig {
    pub show_code: bool,
    pub color: bool,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(default)]
pub struct HooksConfig {
    pub auto_add: bool,
    pub track_patterns: Vec<String>,
}

impl Default for SchedulingConfig {
    fn default() -> Self {
        SchedulingConfig {
            max_interval: 365,
            new_card_limit: 20,
        }
    }
}

impl Default for DisplayConfig {
    fn default() -> Self {
        DisplayConfig {
            show_code: true,
            color: true,
        }
    }
}

impl Default for HooksConfig {
    fn default() -> Self {
        HooksConfig {
            auto_add: true,
            track_patterns: vec![
                r"Co-authored-by:.*Claude".to_string(),
                r"Co-authored-by:.*Copilot".to_string(),
                r"Co-authored-by:.*Cursor".to_string(),
                r"Generated by".to_string(),
            ],
        }
    }
}

impl Config {
    pub fn from_toml(s: &str) -> Result<Self, ConfigError> {
        let config: Config = toml::from_str(s)?;
        config.validate()?;
        Ok(config)
    }

    pub fn load(path: &std::path::Path) -> Result<Self, ConfigError> {
        if !path.exists() {
            return Ok(Config::default());
        }
        let content = std::fs::read_to_string(path)?;
        Self::from_toml(&content)
    }

    fn validate(&self) -> Result<(), ConfigError> {
        for pattern in &self.hooks.track_patterns {
            regex::Regex::new(pattern).map_err(|_| ConfigError::InvalidPattern {
                pattern: pattern.clone(),
            })?;
        }
        Ok(())
    }

    pub fn to_toml_string(&self) -> String {
        format!(
            r#"[scheduling]
max_interval = {}
new_card_limit = {}

[display]
show_code = {}
color = {}

[hooks]
auto_add = {}
track_patterns = [
{}]
# Set to [".*"] to track all commits. Remove patterns to narrow scope.
"#,
            self.scheduling.max_interval,
            self.scheduling.new_card_limit,
            self.display.show_code,
            self.display.color,
            self.hooks.auto_add,
            self.hooks
                .track_patterns
                .iter()
                .map(|p| format!("    \"{}\",", p))
                .collect::<Vec<_>>()
                .join("\n"),
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_full_config() {
        let toml = r#"
[scheduling]
max_interval = 180
new_card_limit = 10

[display]
show_code = false
color = true

[hooks]
auto_add = false
track_patterns = [".*"]
"#;
        let config = Config::from_toml(toml).unwrap();
        assert_eq!(config.scheduling.max_interval, 180);
        assert_eq!(config.scheduling.new_card_limit, 10);
        assert!(!config.display.show_code);
        assert!(!config.hooks.auto_add);
        assert_eq!(config.hooks.track_patterns, vec![".*"]);
    }

    #[test]
    fn parse_empty_uses_defaults() {
        let config = Config::from_toml("").unwrap();
        assert_eq!(config.scheduling.max_interval, 365);
        assert_eq!(config.scheduling.new_card_limit, 20);
        assert!(config.display.show_code);
        assert!(config.hooks.auto_add);
        assert!(!config.hooks.track_patterns.is_empty());
    }

    #[test]
    fn parse_partial_config() {
        let toml = "[scheduling]\nmax_interval = 100\n";
        let config = Config::from_toml(toml).unwrap();
        assert_eq!(config.scheduling.max_interval, 100);
        assert_eq!(config.scheduling.new_card_limit, 20);
        assert!(config.display.show_code);
    }

    #[test]
    fn invalid_toml_is_error() {
        assert!(Config::from_toml("not valid {{toml").is_err());
    }

    #[test]
    fn invalid_regex_is_error() {
        let toml = r#"
[hooks]
track_patterns = ["[invalid"]
"#;
        let err = Config::from_toml(toml).unwrap_err();
        assert!(matches!(err, ConfigError::InvalidPattern { .. }));
    }

    #[test]
    fn default_config_round_trips() {
        let config = Config::default();
        let toml = config.to_toml_string();
        let parsed = Config::from_toml(&toml).unwrap();
        assert_eq!(parsed.scheduling.max_interval, 365);
        assert_eq!(parsed.scheduling.new_card_limit, 20);
    }
}
