base_url = "https://tate.umaru.dev"
title = "Tate"
description = "Understand the code you ship."
compile_sass = true
build_search_index = false
generate_feeds = false
minify_html = true

[markdown]
external_links_target_blank = true

[markdown.highlighting]
enabled = true
theme = "ayu-dark"

[extra]
github_url = "https://github.com/umarudotdev/tate"
tagline = "Understand the code you ship."
